### ISSUE TITLE
(Firefox-only)  Need to hit back button multiple times on pages with code editor

### ISSUE THREAD

**Issue by arata-ae** [gfxfundamentals/live-editor#1]
It seems that there is an issue affecting pages containing a code editor, but only in Firefox (my version: v112). When navigating away from such pages, I need to hit the back button 1 + n times, where n is the number of editors on the page.

Example page: https://webgpufundamentals.org/webgpu/lessons/webgpu-fundamentals.html

It looks like there is a Firefox-specific URL params hack that may be causing this issue in editor.js, but this is just my guess.

**Comment by greggman** [comment]
That is a bug in firefox. I will file it after I make a small repo.  And hopefully find a workaround

**Comment by greggman** [comment]
narrowed down the bug in firefox. Filed

https://bugzilla.mozilla.org/show_bug.cgi?id=1828286

**Comment by greggman** [comment]
sadly I don't know how to workaround the issue. I tried replacing `fetch` with `XHRHttpRequest` but firefox still exhibited the same bug.

**Comment by greggman** [comment]
fixed. Note: you might have to clear your cache or load https://webgpufundamentals.org/webgpu/resources/editor.js and pick refresh
